name: 'Deploy to s3'
inputs:
  bucketName:
    description: bucketName
    required: true
  bucketRegion:
    description: bucketRegion
    required: true
  file:
    description: file
    required: true
    default: dist
outputs:
  website-url:
    description: website-url
runs:
  using: node16
  main: main.js
