name: Cache or install dependencies
description: Cache or install dependencies
inputs:
  caching:
    description: 'whether caching shouldbe done'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether cache was used'
    value: ${{steps.install.outputs.cache}}
runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.caching == 'true'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: | 
        npm ci
        echo "::set-output cache::='${{inputs.caching}}"
      shell: bash